
CREATE TABLE Forms (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(), 
    Title NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX),
    DisplayOrder INT DEFAULT 0,
    Status VARCHAR(50),
    CreatedAt DATETIME2 DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 DEFAULT GETUTCDATE()
);

CREATE TABLE FormFields (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    FormId UNIQUEIDENTIFIER NOT NULL,
    Label NVARCHAR(255) NOT NULL,
    FieldType VARCHAR(50) NOT NULL, 
    DisplayOrder INT DEFAULT 0,
    IsRequired BIT DEFAULT 0,
    Configuration NVARCHAR(MAX) DEFAULT '{}', 
    CreatedAt DATETIME2 DEFAULT GETUTCDATE(),
    CONSTRAINT FK_FormFields_Forms FOREIGN KEY (FormId) REFERENCES Forms(Id) ON DELETE CASCADE,
    CONSTRAINT CHK_FormFields_Config_IsJson CHECK (ISJSON(Configuration) = 1),
    CONSTRAINT UQ_FormFields_FormId_Name UNIQUE (FormId)
);

CREATE TABLE Submissions (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    FormId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER, 
    SubmittedAt DATETIME2 DEFAULT GETUTCDATE(),
    Data NVARCHAR(MAX) NOT NULL DEFAULT '{}',
    CONSTRAINT FK_Submissions_Forms FOREIGN KEY (FormId) REFERENCES Forms(Id) ON DELETE CASCADE,
    CONSTRAINT CHK_Submissions_Data_IsJson CHECK (ISJSON(Data) = 1)
);

-- index
CREATE NONCLUSTERED INDEX IX_FormFields_FormId ON FormFields(FormId);
CREATE NONCLUSTERED INDEX IX_Submissions_FormId ON Submissions(FormId);
CREATE NONCLUSTERED INDEX IX_Submissions_SubmittedAt ON Submissions(SubmittedAt DESC);
